"""Add confirmed_at to contract_calls

Revision ID: 50b15a68399c
Revises: 688ed0c87848
Create Date: 2025-05-21 10:04:10.562661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b15a68399c'
down_revision: Union[str, None] = '688ed0c87848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blocked_addresses_address'), 'blocked_addresses', ['address'], unique=True)
    op.drop_column('blocked_addresses', 'timestamp')
    op.drop_column('blocked_addresses', 'reason')
    op.add_column('contract_calls', sa.Column('from_address', sa.String(), nullable=True))
    op.add_column('contract_calls', sa.Column('to_address', sa.String(), nullable=True))
    op.add_column('contract_calls', sa.Column('call_time', sa.DateTime(), nullable=True))
    op.add_column('contract_calls', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_contract_calls_from_address'), 'contract_calls', ['from_address'], unique=False)
    op.create_index(op.f('ix_contract_calls_to_address'), 'contract_calls', ['to_address'], unique=False)
    op.drop_column('contract_calls', 'timestamp')
    op.drop_column('contract_calls', 'sender')
    op.drop_column('contract_calls', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_calls', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('contract_calls', sa.Column('sender', sa.VARCHAR(), nullable=True))
    op.add_column('contract_calls', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_contract_calls_to_address'), table_name='contract_calls')
    op.drop_index(op.f('ix_contract_calls_from_address'), table_name='contract_calls')
    op.drop_column('contract_calls', 'confirmed_at')
    op.drop_column('contract_calls', 'call_time')
    op.drop_column('contract_calls', 'to_address')
    op.drop_column('contract_calls', 'from_address')
    op.add_column('blocked_addresses', sa.Column('reason', sa.VARCHAR(), nullable=True))
    op.add_column('blocked_addresses', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_blocked_addresses_address'), table_name='blocked_addresses')
    # ### end Alembic commands ###
