"""Initial migration

Revision ID: 688ed0c87848
Revises: 
Create Date: 2025-05-20 13:16:33.649293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688ed0c87848'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_blocked_addresses_id'), 'blocked_addresses', ['id'], unique=False)
    op.create_table('contract_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_calls_id'), 'contract_calls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_calls_id'), table_name='contract_calls')
    op.drop_table('contract_calls')
    op.drop_index(op.f('ix_blocked_addresses_id'), table_name='blocked_addresses')
    op.drop_table('blocked_addresses')
    # ### end Alembic commands ###
